export const VIDEO_ASSISTANT_SCOPE_MESSAGE =
  "I can't help with that here. Tell me what kind of video you want to make, paste a script, or attach a reference image.";

const ALLOWED_TERMS = [
  "video",
  "motion",
  "animation",
  "animate",
  "remotion",
  "render",
  "renderer",
  "template",
  "scene",
  "timeline",
  "frame",
  "fps",
  "aspect",
  "mp4",
  "component",
  "import",
  "export",
  "bundle",
  "webpack",
  "lottie",
  "caption",
  "subtitle",
  "narration",
  "voiceover",
  "audio",
  "tts",
  "piper",
  "elevenlabs",
  "music",
  "sound",
  "transition",
  "typography",
  "layout",
  "design",
  "storyboard",
  "script",
  "reference",
  "idea",
  "prompt",
  "promo",
  "ad",
  "advertisement",
  "commercial",
  "explainer",
  "intro",
  "outro",
  "reel",
  "social",
  "instagram",
  "tiktok",
  "youtube",
  "shorts",
  "launch",
  "campaign",
  "brand",
  "product",
  "saas",
  "software",
  "app",
  "api",
  "backend",
  "frontend",
  "database",
  "mongodb",
  "worker",
  "canvas",
  "editor",
];

const OFF_TOPIC_TERMS = [
  "capital of",
  "weather",
  "stock price",
  "sports score",
  "recipe",
  "homework",
  "medical",
  "legal advice",
  "politics",
  "dating",
  "joke",
  "poem",
  "song lyrics",
  "translate",
];

// Topic guard removed — any non-empty prompt is allowed. (Kept the function so
// existing call sites keep working; ALLOWED_TERMS/OFF_TOPIC_TERMS retained for
// reference in case a lighter guard is ever wanted again.)
export function isVideoAssistantTopic(input: string) {
  return String(input || "").trim().length > 0;
}
